config/routes.rb
Rails.application.routes.draw do

	get "history_back" => "history_back#index"

        devise_for :users, controllers: {
                sessions: "auth/sessions",
                confirmations: "auth/sessions",
                omniauth: "auth/omniauth",
                passwords: "auth/passwords",
                registrations: "auth/registrations",
                unlocks: "auth/unlocks"
        }
        get "users/captcha" => "auth/captcha#index"
	post "redactor_rails/pictures" => "images#create"
	post "topics/:id/like" => "topics#like"
	get "topics/search" => "topics#search"

	post "image" => "images#create"

	resources :topics do
		resources :posts
	end
	post "topics/:tid/enroll" => "enrolls#create"
	get "topics/:id/enroll" => "enrolls#index"
	get "topics/:id/new_enroll" => "enrolls#new"
	get "enrolls/:id" => "enrolls#show"
	post "enrolls/:id/confirm" => "enrolls#confirm"

	get "customer_sign_in" => "users#customer_sign_in"
	post "customer_sign_in" => "users#customer_sign_in_check"

	get "activities" => "topics#activities"

        resources :categories
	resources :users
	get "user/enrolls" => "users#enrolls"

	get 'payment/alipay/redirect' => 'payments#alipay_redirect'
	get 'payment/alipay/front_notify' => 'payments#alipay_front_notify'
	post 'payment/alipay/notify' => 'payments#alipay_notify'

	get "chat/:enroll_id" => "chat#index"
	post "chat/:topic_id" => "chat#create"
	get "chat/:topic_id/latest" => "chat#latest"
	get "chat/:topic_id/history" => "chat#history"

	post "images" => "images#create"

        root "topics#activities"

end

app/models/topic.rb
require 'elasticsearch/model'
class Topic < ActiveRecord::Base
        has_many :posts
        has_many :enrolls
        belongs_to :user
        has_many :user_favorites
        has_many :questions
        accepts_nested_attributes_for :questions

        validates :title, presence: true
        validates :content, presence: true

        before_create do
                self.favorite = 0
        end

        # full text index
        include Elasticsearch::Model
        include Elasticsearch::Model::Callbacks

        def as_indexed_json(options = {})
                as_json(only: ["id", "title"])
        end

        def self.search(search_text)
                search_params = {
                        query: {
                                match: { title: search_text }
                        },
                        from: 0,
                        size: 50
                }
                __elasticsearch__.search(search_params).records
        end

        def need_payment?
                enroll_fee.present?
        end

        def has_questions?
                questions.any?
        end

        def enroll_started?
                Time.current >= enroll_start_date
        end

        def enroll_ended?
                Time.current > enroll_end_date
        end

        def enroll_finished?
                enrolls.size >= max_places
        end

end
Topic.import # for auto sync model with elastic search

app/controllers/topics_controller.rb
# -*- coding: utf-8 -*-
class TopicsController < ApplicationController
        before_action :set_topic, only: [:edit, :update, :destroy]
        before_action :authenticate_user!, except: [:index, :show, :activities]
        load_and_authorize_resource

        # GET /topics
        # GET /topics.json
        def index
                categories = Category.all
                # Save param info, used in back button
                session["category"] = params[:category] if params[:category].present?
                session["category"] = categories[0].id if categories.any? && session["category"].nil?
                session["page"] = params[:page] if params[:page].present?
                @topics = Topic.where(category_id: session["category"]).order(priority: :desc, id: :desc).paginate(page: session["page"])
                @menus = []
                categories.each do |c|
                        @menus << {
                                name: c.name,
                                href: "#{topics_url}?category=#{c.id}",
                                class: c.id.eql?(session[:category].to_i) ? "active" : ""
                        }
                end
        end

        # GET /topics/1
        # GET /topics/1.json
        def show
                @topic = Topic.find(params[:id])
                if @topic.enroll && session[:user_tel].present?
                        @user_enroll_info = Enroll.where(tel: session[:user_tel], topic_id: @topic.id).first
                end
                create_access_log
                set_back_url
                render :activity_detail if @topic.enroll
        end

        # GET /topics/new
        def new
                @topic = Topic.new
                set_back_url
                render :new_activity if current_user.partener?
        end

        # GET /topics/1/edit
        def edit
                @back_url = topic_path(@topic)
                render :edit_activity if current_user.partener?
        end

        # POST /topics
        # POST /topics.json
        def create
                @topic = Topic.new(topic_params)
                @topic.user = current_user

                respond_to do |format|
                        if @topic.save
                                format.html { redirect_to @topic, notice: "创建成功" }
                                format.json { render :show, status: :created, location: @topic }
                        else
                                format.html {
                                        render :new if current_user.admin?
                                        render :new_activity if current_user.partener?
                                }
                                format.json { render json: @topic.errors, status: :unprocessable_entity }
                        end
                end
        end

        # PATCH/PUT /topics/1
        # PATCH/PUT /topics/1.json
        def update
                respond_to do |format|
                        if @topic.update(topic_params)
                                format.html { redirect_to @topic, notice: "更新成功" }
                                format.json { render :show, status: :ok, location: @topic }
                        else
                                format.html { render :edit }
                                format.json { render json: @topic.errors, status: :unprocessable_entity }
                        end
                end
        end

        # DELETE /topics/1
        # DELETE /topics/1.json
        def destroy
                @topic.destroy
                respond_to do |format|
                        format.html { redirect_to topics_url, notice: "\"#{@topic.title}\"已成功删除" }
                        format.json { head :no_content }
                end
        end

        # POST /topics/1/like.json
        def like
                fav = UserFavorite.where(user_id: current_user.id, topic_id: params[:id])
                if fav.present?
                        render plain: "marked_before"
                else
                        fav = UserFavorite.new
                        fav.user_id = current_user.id
                        fav.topic_id = params[:id]
                        fav.save!
                        render plain: "marked"
                end
        end

        # GET /topics/search
        def search
                @search_text = params[:search_text]
                @topics = Topic.search(@search_text)
                @back_url = topics_url
        end

        def activities
                @activities = Topic.where(category_id: nil).order(priority: :desc, id: :desc).paginate(page: session["page"])
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_topic
                @topic = Topic.find(params[:id])
                render_404 if current_user.user? && !@topic.user_id.eql?(current_user.id)
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def topic_params
                params[:topic].permit(:title, :category_id, :content, :priority, :enroll, :enroll_fee, :enroll_promotion, :desc, :cover_image,
                                      :enroll_start_date, :enroll_end_date, :datetime, :start_time, :location, :min_places, :max_places,
                                      questions_attributes: [:id, :content, :required])
        end

        def set_back_url
                if @topic.present? && @topic.category_id.nil?
                        @back_url = "/activities"
                else
                        @back_url = topics_path
                end
        end

        def create_access_log
                access_log = AccessLog.new
                access_log.resource_name = :topic
                access_log.resource_id = params[:id]
                access_log.user_id = current_user.id if current_user.present?
                access_log.save!
        end
end

app/helpers/topics_helper.rb
# -*- coding: utf-8 -*-
module TopicsHelper

        def progress(activity)
                progress = activity.enrolls.size.to_f / activity.max_places.to_f * 100
                progress = 100 if progress >= 100
                progress.to_s + "%"
        end

        def enroll_count(activity)
                enroll_size = activity.enrolls.size
                txt = "#{activity.min_places} ~ #{activity.max_places}人"
                txt << " #{enroll_size}人已报名" if enroll_size > 0
                txt
        end

end

app/views/topics/_activity_form.html.erb
<%= form_for(@topic, html: {onsubmit: "return topics.setFormParams()"}) do |f| %>
<% if @topic.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @topic.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<input type="hidden" name="topic[enroll]" value="1">

<div class="form-horizontal">
  <div class="form-group">
    <%=f.label :title, "标题", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :title, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :desc, "简介", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :desc, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :enroll_start_date, "报名开始时间", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :enroll_start_date, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :enroll_start_date, "报名截止时间", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :enroll_end_date, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :start_time, "活动时间", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :start_time, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :location, "地址", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.text_field :location, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :min_places, "报名目标人数下限", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.number_field :min_places, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :max_places, "报名目标人数上限", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-5 col-xs-12">
      <%=f.number_field :max_places, class: "form-control", required: true%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cover_image, class: "col-sm-2 control-label" do %>
    封面图片 <span class="glyphicon glyphicon-info-sign icon" title="该图片将作为商品封面，为了保证显示效果，请使用256*256的图片并使用透明背景"></span>
    <% end %>
    <div class="col-sm-5">
      <% if f.object.cover_image.nil? %>
      <%= image_tag "empty-img.png", class: "img-thumbnail", onclick: "uploader.open()", id: "cover_image", style: "width:180px" %>
      <% else %>
      <%= image_tag f.object.cover_image, class: "img-thumbnail", onclick: "uploader.open()", id: "cover_image", style: "width:180px" %>
      <% end %>
      <div class="progress upload-progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
          <span class="sr-only">100% Complete</span>
        </div>
      </div>
      <%= f.hidden_field :cover_image %>
    </div>
  </div>

  <div class="form-group" id="questions">
    <label class="col-md-1 col-xs-12 control-label">表格</label>
    <div class="col-md-11 col-xs-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="display:none"></th><th style="width:80%;">题目</th><th>必填</th><th>删除</th>
          </tr>
        </thead>
        <tbody id="questions_tbody">
          <% @topic.questions.each do |question| %>
          <tr>
            <td style="display:none"><input type="hidden" value="<%=question.id%>"></td>
            <td><input type="text" class="form-control" value="<%=question.content%>"></td>
            <td><input type="checkbox" <%if question.required%>checked="checked"<%end%>></td>
            <td>
              <button type="button" class="btn btn-danger" onclick="topics.removeQuestion(this)" title="删除">
                <span class='glyphicon glyphicon-trash' style='color:#fff;'></span>
              </button>
            </td>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="9">
              <a href="javascript:topics.addQuestion()" class="btn btn-default">
                <span class='glyphicon glyphicon-plus'></span> 增加题目
              </a>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
    <label class="col-md-1 col-xs-12 control-label">报名收费</label>
    <div class="col-md-11 col-xs-12">
      <div class="input-group">
        <div class="input-group-addon">￥</div>
        <%=f.number_field :enroll_fee, class: "form-control", min: 1, step: 1%>
      </div>
    </div>
    <label class="col-md-1 col-xs-12 control-label">优惠</label>
    <div class="col-md-11 col-xs-12">
      <div class="input-group">
        <div class="input-group-addon">￥</div>
        <%=f.number_field :enroll_promotion, class: "form-control", min: 0, step: 1%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%=f.label :content, "内容", class: "control-label col-md-1 col-xs-12"%>
    <div class="col-md-8 col-xs-12">
      <%=f.text_area :content, class: "redactor"%>
    </div>
  </div>
</div>

<div class="actions col-md-offset-1">
  <%= f.submit "确认", class: "btn btn-primary" %>
</div>
<% end %>

<script type="text/template" id="question_template">
  <tr>
    <td style="display:none"><input type="hidden"></td>
    <td><input type="text" class="form-control"></td>
    <td><input type="checkbox"></td>
    <td>
      <button type="button" class="btn btn-danger" onclick="topics.removeQuestion(this)" title="删除">
        <span class='glyphicon glyphicon-trash' style='color:#fff;'></span>
      </button>
    </td>
  </tr>
</script>

<input type="file" name="image" id="cover_image_upload" style="visibility: hidden;" onchange="uploader.upload(event);">

app/views/topics/_form.html.erb
<%= form_for(@topic, html: {onsubmit: "return topics.setFormParams()"}) do |f| %>
  <% if @topic.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
    <div class="form-group">
      <%=f.label :title, "标题", class: "control-label col-md-1 col-xs-12"%>
      <div class="col-md-5 col-xs-12">
        <%=f.text_field :title, class: "form-control", required: true%>
      </div>
    </div>

    <div class="form-group">
      <%=f.label :category_id, "板块", class: "control-label col-md-1 col-xs-12"%>
      <div class="col-md-5 col-xs-12">
        <%=f.select :category_id, Category.all.collect{|c| [c.name, c.id]}, {}, class: "form-control", required: true%>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-11 col-xs-12 col-md-offset-1">
        <%= f.check_box :priority %>
        <%= f.label :priority, class: "control-label" do %>
        置顶
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-11 col-xs-12 col-md-offset-1">
        <%= f.check_box :enroll, onchange: "topics.enableEnroll(this.checked)" %>
        <%= label_tag :enroll, class: "control-label" do %>
        报名
        <% end %>
      </div>
    </div>

    <div class="form-group" id="questions" <% if !@topic.enroll %>style="display:none;"<% end %>>
      <label class="col-md-1 col-xs-12 control-label">表格</label>
      <div class="col-md-11 col-xs-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="display:none"></th><th style="width:80%;">题目</th><th>必填</th><th>删除</th>
            </tr>
          </thead>
          <tbody id="questions_tbody">
            <% @topic.questions.each do |question| %>
            <tr>
              <td style="display:none"><input type="hidden" value="<%=question.id%>"></td>
              <td><input type="text" class="form-control" value="<%=question.content%>"></td>
              <td><input type="checkbox" <%if question.required%>checked="checked"<%end%>></td>
              <td>
                <button type="button" class="btn btn-danger" onclick="topics.removeQuestion(this)" title="删除">
                  <span class='glyphicon glyphicon-trash' style='color:#fff;'></span>
                </button>
              </td>
            </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="9">
                <a href="javascript:topics.addQuestion()" class="btn btn-default">
                  <span class='glyphicon glyphicon-plus'></span> 增加题目
                </a>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
      <label class="col-md-1 col-xs-12 control-label">报名收费</label>
      <div class="col-md-11 col-xs-12">
        <div class="input-group">
          <div class="input-group-addon">￥</div>
          <%=f.number_field :enroll_fee, class: "form-control", min: 1, step: 1%>
        </div>
      </div>
      <label class="col-md-1 col-xs-12 control-label">优惠</label>
      <div class="col-md-11 col-xs-12">
        <div class="input-group">
          <div class="input-group-addon">￥</div>
          <%=f.number_field :enroll_promotion, class: "form-control", min: 0, step: 1%>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%=f.label :content, "内容", class: "control-label col-md-1 col-xs-12"%>
      <div class="col-md-8 col-xs-12">
        <%=f.text_area :content, class: "redactor"%>
      </div>
    </div>
  </div>

  <div class="actions col-md-offset-1">
    <%= f.submit "确认", class: "btn btn-primary" %>
  </div>
<% end %>

<script type="text/template" id="question_template">
  <tr>
    <td style="display:none"><input type="hidden"></td>
    <td><input type="text" class="form-control"></td>
    <td><input type="checkbox"></td>
    <td>
      <button type="button" class="btn btn-danger" onclick="topics.removeQuestion(this)" title="删除">
        <span class='glyphicon glyphicon-trash' style='color:#fff;'></span>
      </button>
    </td>
  </tr>
</script>

app/views/topics/_topic.html.erb
<% if topic.need_payment? %>
<li>
  <%=link_to topic_path(topic), class: "flex-container" do%>
  <div class="flex-item">
    <h3 class="enroll">
      <%=topic.title%>
    </h3>
  </div>
  <% end %>
</li>
<% else %>
<li>
  <%=link_to topic_path(topic), class: "flex-container" do%>
  <div class="avatar topic-avatar">
    <%=avatar topic.user%>
  </div>
  <div class="flex-item">
    <h3 class="<%= 'top' if topic.priority%>">
      <%=topic.title%>
    </h3>
    <div class="info">
      <span class="pull-left"><%=topic.user.name%></span>
      <span class="pull-right"><i class="glyphicon glyphicon-thumbs-up"></i> <%=topic.user_favorites.size%></span>
    </div>
  </div>
  <% end %>
</li>
<% end %>

app/views/topics/activities.html.erb
<div class="forum-entrance">
  <div class="row">
    <%= image_tag "cover.jpg" %>
    <p>教育最需要平等，为更多孩子打开世界的大门，定期北京、台湾、香港交流与海外国际学校短期出国留学体验活动，用心发觉每个孩子的才能，帮助筹划申请国际名校海外大学。</p>
    <div class="activity-actions">
      <a  href="/topics" class="btn">进入论坛</a>
    </div>
  </div>
</div>

<div class="activities-container row">
  <h1>昆明近期活动</h1>
  <% @activities.each do |activity| %>
  <div class="activity">
    <div class="activity-title">
      <div class="activity-title-text">
        <span class="activity-headline"><%=activity.title %></span>
        <span class="activity-subhead"><%=activity.desc %></span>
      </div>
      <div class="activity-media">
        <img src="<%=activity.cover_image%>">
      </div>
    </div>
    <div class="action-body">
      <ul class="activity-info">
        <li>
          <i class="glyphicon glyphicon-time"></i>
          <span class="info"><%=display_datetime_zh activity.start_time%></span>
        </li>
        <li>
          <i class="glyphicon glyphicon-map-marker"></i>
          <span class="info"><%=activity.location%></span>
        </li>
      </ul>
      <div class="sales-progress">
        <div class="sales-progressbar">
          <div class="sales-info">报名人数：<%=activity.enrolls.size%></div>
          <div class="sales-progressbar-indicator" style="width:<%=progress activity%>"></div>
        </div>
      </div>
      <div class="activity-status">
        <%= "报名尚未开始" unless activity.enroll_started? %>
        <%= "报名已经结束" if activity.enroll_ended? %>
        <%= "名额已满" if activity.enroll_finished? %>
      </div>
    </div>
    <div class="activity-actions">
      <% if current_user.present? && current_user.id.eql?(activity.user_id) %>
      <%= link_to "删除", topic_url(activity), method: "delete", class: "btn btn-danger",  data: { confirm: "确实要删除\"#{activity.title}\"吗？" } %>
      <%= link_to "修改", "/topics/#{activity.id}/edit", class: "btn" %>
      <%= link_to "报名情况", "/topics/#{activity.id}/enroll", class: "btn" %>
      <% else %>
      <% end %>
      <%= link_to "查看", topic_url(activity), class: "btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<h2>编辑帖子</h2>
<%=link_to topic_url(@topic), method: "delete", class: "btn btn-primary pull-right", style: "position:relative;top:-44px;", data: {confirm: "确定要删除吗？"} do %>
<i class="glyphicon glyphicon-trash"></i> 删除
<% end %>

<%= render 'form' %>

app/views/topics/edit_activity.html.erb
<h3 class="page-header">修改活动</h3>
<%= render "activity_form" %>

app/views/topics/index.html.erb
<div class="row">
  <ul class="list">
    <% @topics.each do |topic| %>
      <%= render partial: "topic", locals: {topic: topic} %>
    <% end %>
  </ul>
</div>
<div class="row">
  <div class="list-footer">
    <%= paginate_info @topics %>
    <%= will_paginate @topics, class: "apple_pagination" %>
  </div>
</div>


<div class="search">
  <%= form_tag "/topics/search", method: "get", class: "flex-container" do %>
  <button type="button" onclick="topics.closeSearch()"><i class="glyphicon glyphicon-arrow-left"></i></button>
  <div class="flex-item">
    <input type="search" name="search_text" id="searchText" required="true" placeholder="搜索帖子" autocomplete="off"></input>
  </div>
  <button type="submit"><i class="glyphicon glyphicon-search"></i></button>
  <% end %>
</div>

app/views/topics/new.html.erb
<h3 class="page-header">创建帖子</h3>

<%= render "form" %>

app/views/topics/new_activity.html.erb
<h3 class="page-header">创建活动</h3>
<%= render "activity_form" %>

app/views/topics/search.html.erb
<div class="row">
  <p style="padding: 20px;background: #fff;">
    <% if @topics.empty? %>
    没有找到与“<%=@search_text%>”相关的内容
    <% else %>
    “<%=@search_text%>”的搜索结果
    <% end %>
  </p>
  <ul class="list">
    <% @topics.each do |topic| %>
    <%= render partial: "topic", locals: {topic: topic} %>
    <% end %>
  </ul>
</div>

app/views/topics/show.html.erb
<input type="hidden" id="topicId" value="<%=@topic.id%>">

<div class="topic-header">
  <h2><%=@topic.title%></h2>
  <div class="control-group">
    <% if current_user.present? && current_user.admin? %>
      <%= link_to edit_topic_path(@topic), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-edit"></i> 编辑
      <% end %>
    <% end %>
    <% if current_user.present? && !@topic.need_payment? %>
      <a href="#new_post" class="btn btn-default">
        <i class="glyphicon glyphicon-share-alt"></i> 回复
      </a>
    <% end %>
  </div>
</div>

<div class="row">
  <% unless @topic.need_payment?%>
  <div class="col-xs-6 col-md-8 topic-user-info user-info">
    <%=avatar @topic.user, class: "avatar" %>
    <p class="user-name"><%=@topic.user.name%></p>
  </div>

  <% if current_user.present? %>
    <div class="col-xs-6 col-md-4">
      <button onclick="topics.like(<%=@topic.id%>)" class="like-btn">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span id="favCount"><%= @topic.user_favorites.size %></span>
      </button>
      <div class="fav-alert" id="favAlert">已评价</div>
    </div>
  <% end %>
  <% end %>
  <div class="col-md-10 col-xs-12">
    <div class="topic-content">
      <%= @topic.content.html_safe %>
    </div>
    <% if @user_enroll_info.present? %>
    <p class="text-success text-center">已经报名！</p>
    <% else %>
    <% if @topic.has_questions? %>
    <%= link_to "报名", "/topics/#{@topic.id}/new_enroll", class: "btn btn-primary btn-block" %>
    <% else %>
    <%= link_to "报名", "/topics/#{@topic.id}/enroll", class: "btn btn-primary btn-block", method: "POST" %>
    <% end %>
    <% end %>

  </div>
  <div class="col-xs-12 col-md-12 topic-info">
    <span class="pull-left">发表于：<%=display_datetime @topic.created_at%></span>
    <button class="back-to-top" id="toTop" onclick="utility.toTop()">
      <i class="glyphicon glyphicon-arrow-up"></i> Top
    </button>
  </div>
</div>

<%= link_to("查看报名情况", "/topics/#{@topic.id}/enroll", class: "pull-right") if current_user.present? && current_user.admin? %>

<% unless @topic.need_payment? %>
<div class="posts row">
  <div class="col-xs-12 col-sm-2">
    <h3>评论</h3>
  </div>
  <div class="col-xs-12 col-sm-10">
    <%=image_tag "spinner.gif", id: "spinner", class: "spinner" %>
    <iframe frameborder="0" scrolling="no" width="100%" height="0" id="posts" name="posts">
    </iframe>
  </div>
</div>

<% if current_user.present? %>
  <div class="new-post">
    <%= form_for([@topic, @topic.posts.build], html: {target: "posts"}) do |f|%>
      <div class="row">
        <%=f.label :content, "回复", class: "control-label col-md-2 col-xs-12"%>
        <div class="col-md-10 col-xs-12">
          <%=f.text_area :content, class: "redactor", required: true%>
        </div>
      </div>
      <div class="actions col-md-offset-2">
        <%= f.submit "确认", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
<% end %>
<% end %>