config/routes.rb
Rails.application.routes.draw do

	get "history_back" => "history_back#index"

        devise_for :users, controllers: {
                sessions: "auth/sessions",
                confirmations: "auth/sessions",
                omniauth: "auth/omniauth",
                passwords: "auth/passwords",
                registrations: "auth/registrations",
                unlocks: "auth/unlocks"
        }
        get "users/captcha" => "auth/captcha#index"
	post "redactor_rails/pictures" => "images#create"
	post "topics/:id/like" => "topics#like"
	get "topics/search" => "topics#search"

	post "image" => "images#create"

	resources :topics do
		resources :posts
	end
	post "topics/:tid/enroll" => "enrolls#create"
	get "topics/:id/enroll" => "enrolls#index"
	get "topics/:id/new_enroll" => "enrolls#new"
	get "enrolls/:id" => "enrolls#show"
	post "enrolls/:id/confirm" => "enrolls#confirm"

	get "customer_sign_in" => "users#customer_sign_in"
	post "customer_sign_in" => "users#customer_sign_in_check"

	get "activities" => "topics#activities"

        resources :categories
	resources :users
	get "user/enrolls" => "users#enrolls"

	get 'payment/alipay/redirect' => 'payments#alipay_redirect'
	get 'payment/alipay/front_notify' => 'payments#alipay_front_notify'
	post 'payment/alipay/notify' => 'payments#alipay_notify'

	get "chat/:enroll_id" => "chat#index"
	post "chat/:topic_id" => "chat#create"
	get "chat/:topic_id/latest" => "chat#latest"
	get "chat/:topic_id/history" => "chat#history"

	post "images" => "images#create"

        root "topics#activities"

end

app/models/post.rb
class Post < ActiveRecord::Base
        belongs_to :topic
        belongs_to :user

end

app/controllers/posts_controller.rb
# -*- coding: utf-8 -*-
class PostsController < ApplicationController
        before_action :set_post, only: [:destroy]
        before_action :authenticate_user!, except: [:index]
        load_and_authorize_resource

        # GET /posts
        # GET /posts.json
        def index
                @topic_id = params[:topic_id]
                @posts = Post.where(topic_id: @topic_id).paginate(page: params["page"])
                render layout: false
        end

        # POST /posts
        # POST /posts.json
        def create
                @topic = Topic.find(params[:topic_id])
                return render 404 unless @topic.present?
                @post = @topic.posts.new(post_params)
                @post.user = current_user

                respond_to do |format|
                        if @post.save!
                                format.html { redirect_to topic_posts_url(params[:topic_id]), notice: "评论发表成功！" }
                                format.json { render :show, status: :created, location: @post }
                        else
                                format.html { redirect_to topic_posts_url(params[:topic_id]), notice: "评论发表失败！" }
                                format.json { render json: @post.errors, status: :unprocessable_entity }
                        end
                end
        end

        # DELETE /posts/1
        # DELETE /posts/1.json
        def destroy
                @post.destroy
                respond_to do |format|
                        format.html { redirect_to topic_posts_url(params[:topic_id]), notice: "已成功删除" }
                        format.json { head :no_content }
                end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
                @post = Post.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
                params.require(:post).permit(:content)
        end

end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div>
      <% if notice.present? %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
      <% end %>
      <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
      <% end %>
    </div>

    <div>
      <% @posts.each do |p| %>
        <div>
          <div class="post">
            <div class="col-xs-2 col-md-2 user-info">
              <%= avatar p.user, class: "avatar" %>
              <p class="user-name"><%=p.user.name%></p>
            </div>
            <div class="col-xs-10 col-md-10 content">
              <% if current_user.present? && current_user.admin? %>
              <%= link_to topic_post_url(@topic_id, p), method: "delete", class: "close pull-right", data: {confirm: "确定要删除这个回复吗？"} do %>
              <span aria-hidden="true">&times;</span>
              <% end %>
              <% end %>
              <%=p.content.html_safe%>
              <div class="info">
                <span>发表于：<%=display_datetime p.created_at%></span>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <div class="">
        <div>
          <%= paginate_info @posts %>
          <%= will_paginate @posts, class: "apple_pagination" %>
        </div>
      </div>

    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>