config/routes.rb
Rails.application.routes.draw do

	get "history_back" => "history_back#index"

        devise_for :users, controllers: {
                sessions: "auth/sessions",
                confirmations: "auth/sessions",
                omniauth: "auth/omniauth",
                passwords: "auth/passwords",
                registrations: "auth/registrations",
                unlocks: "auth/unlocks"
        }
        get "users/captcha" => "auth/captcha#index"
	post "redactor_rails/pictures" => "images#create"
	post "topics/:id/like" => "topics#like"
	get "topics/search" => "topics#search"

	post "image" => "images#create"

	resources :topics do
		resources :posts
	end
	post "topics/:tid/enroll" => "enrolls#create"
	get "topics/:id/enroll" => "enrolls#index"
	get "topics/:id/new_enroll" => "enrolls#new"
	get "enrolls/:id" => "enrolls#show"
	post "enrolls/:id/confirm" => "enrolls#confirm"

	get "customer_sign_in" => "users#customer_sign_in"
	post "customer_sign_in" => "users#customer_sign_in_check"

	get "activities" => "topics#activities"

        resources :categories
	resources :users
	get "user/enrolls" => "users#enrolls"

	get 'payment/alipay/redirect' => 'payments#alipay_redirect'
	get 'payment/alipay/front_notify' => 'payments#alipay_front_notify'
	post 'payment/alipay/notify' => 'payments#alipay_notify'

	get "chat/:enroll_id" => "chat#index"
	post "chat/:topic_id" => "chat#create"
	get "chat/:topic_id/latest" => "chat#latest"
	get "chat/:topic_id/history" => "chat#history"

	post "images" => "images#create"

        root "topics#activities"

end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="nav-top">
    <% if @back_url.present? %>
      <button class="pull-left icon btn" onclick="window.location.href=('<%=@back_url%>')"><i class="glyphicon glyphicon-arrow-left"></i></button>
    <% end %>
    <div style="display: inline-block;" class="inherit-height">
      <div class="table-center-wrap inherit-height">
        <h1 class="brand table-center"><%= @title.present? ? @title : "HelloWorld北京国际教育互促会" %></h1>
      </div>
    </div>
    <button class="pull-right icon btn" onclick="nav.toggleSettings();"><i class="glyphicon glyphicon-option-vertical"></i></button>
  </div>
  <% if @menus.present? %>
    <div class="nav-bottom">
      <div class="left scroll-indicator" onclick="nav.scrollLeft()"><i class="glyphicon glyphicon-menu-left"></i></div>
      <div class="scroll-container" onscroll="nav.setScrollIndicator()">
        <ul>
          <% @menus.each do |m| %>
            <li class="<%=m[:class]%>"><h2><%= link_to m[:name], m[:href] %></h2></li>
          <% end %>
        </ul>
      </div>
      <div class="right scroll-indicator" onclick="nav.scrollRight()"><i class="glyphicon glyphicon-menu-right"></i></div>
    </div>
  <% end %>
</header>

<div>
  <% if notice.present? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld北京国际教育互促会</title>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <link href="<%=image_url('favicon.ico')%>" rel="icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>

    <div class="card settings">
      <ul>
        <% if current_user.present? && current_user.admin? %>
          <li><%=link_to "创建帖子", new_topic_path %></li>
          <li><%=link_to "管理板块", categories_path %></li>
          <li><%=link_to "管理用户", users_path %></li>
        <% end %>
        <% if current_user.present? && current_user.partener? %>
        <li><%=link_to "创建活动", new_topic_path %></li>
        <% end %>
        <% if current_user.present? %>
          <li><%=link_to "账户设置", edit_user_path(current_user) %></li>
        <% end %>
        <li><%=link_to "搜索帖子", "###", onclick: "topics && topics.openSearch()" %></li>
        <li><a href="/users/sign_in">登录/注册</a></li>
        <li><%=link_to "我的报名", "/user/enrolls" %></li>
      </ul>
    </div>


    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <p class="copyright">Copyright © 2016 HelloWorld北京国际教育互促会</p>
        <ul>
          <li>京ICP备15036211号</li>
        </ul>
      </div>
    </footer>

    <div class="block-layer"></div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag params[:controller] %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld北京国际教育互促会</title>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <link href="<%=image_url('favicon.ico')%>" rel="icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>
    <div class="container auth-container">
      <div class="row">
        <div class="col-md-7 col-sm-7 not-small-screen">
          <div class="auth-cover"></div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "jquery.js" %>
    <%= javascript_include_tag "devise.js", "data-turbolinks-track" => true %>
  </body>
</html>